<a href="https://colab.research.google.com/github/leesolhahaha/Data_Analysis_with_Python/blob/main/01_numpy_%EA%B8%B0%EC%B4%88_axis%2C_random%2C_ravel%2C_flatten%2C_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy 모듈 불러오기
import numpy as np

* numpy는 기본적으로 C언어로 구현되어 있습니다. - 속도가 빠르다.
* 수치 연산에 관련된 방대한 라이브러리가 존재. ( with scipy )
* 일반 파이썬을 이용한 수치 연산보다 훨씬 빠르다.
* 특히 배열 병렬 연산에 특화 되어 있다.

# 1. numpy의 배열을 ndarray
- `ndarray` : 넘파이에서 사용하는 자료구조 형태

In [ ]:
# 1. python의 list를 ndarray로 만들기
py_list = [1, 2, 3]

arr1 = np.array(py_list) # np.array : 파이썬의 리스트를 ndarray화
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1[0]

1

In [ ]:
arr1[-1]

3

## 배열의 종류
1. 스칼라(scalar)
  * 0차원 데이터
  * 측정한 하나의 값
    - ```python
        height = 180.1
        age = 34
        weight = 80.5
      ```
2. 벡터(vector)
  * 1차원 배열
  * **스칼라가 연속적으로 모여있는 것**
  * 3명의 키를 하나의 배열로 모을 수 있겠죠?
    * ```python
        person_heights = [180.1, 173.5, 177.8] # 3차원 벡터
      ```
  * 벡터 내에 데이터가 `N`개가 있으면 `N 차원 벡터`라고 한다.
    - 수학적인 표현
3. 행렬(matrix)
  * 2차원 배열
  * 1차원 배열인 벡터가 여러 개 모여있는 것.
    * ```python
      person_info = [[180.1, 33, 80.5],
                      [175.1, 32, 77.3]]
    ```
4. 텐서(tensor)
  * 3차원 이상의 배열을 의미한다.
  * 3차원 배열은 2차원 배열이 모여있는 것
  * 4차원 배열은 3차원 배열이 모여있는 것
  * `N차원 배열`을 그냥 텐서라고 한다. (`N`이 꼭 3부터는 아님..)
  * 텐서의 개념을 활용하면 모든 배열의 모양을 이야기 할 수 있다.
    - `0 Rank Tensor` - 스칼라
    - `1 Rank Tensor` - 벡터
    - `2 Rank Tensor` - 행렬
    - `3 Rank Tensor` - 3 Rank Tensor...
  * Tensorflow는 뭘까요..?
    - 구글에서 제공하는 딥러닝 프레임워크
    - 미리 준비된 네트워크에 Tensor를 흘린다(flow)



# numpy 함수 알아보기

In [ ]:
# np.arange - 파이썬의 range와 매우 흡사
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [ ]:
# np.zeros -> 0으로 채워진 배열을 만들 때 사용
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# ,가 추가 될 때마다 차원이 확장이 됨

In [ ]:
# np.zeros에 형상정보(shape)을 입력해 배열 생성 가능!
# shpae을 할 떄는 () 튜플 형태로 만들어주면 됨
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 2차원 배열을 만들기 위해서는 1차원 배열의 개수가 필요함
# 1차원 배열의 개수를 만들기 위해서는 0차원 스칼라의 개수가 필요함

In [ ]:
np.zeros((3,5,4)) # 3차원 배열을 만들기 위해서는 위의 법칙을 따라가면 됨
# 2차원 배열이 3개 1차원 배열이 5개 각각의 1차원 배열 안쪽에 스칼라가 4개 있는 거 3차원 배열이 만들어짐

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((3, 4, 5, 2)) # 4차원 배열

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
       

In [ ]:
# np.zeros((5)) # 이렇게 한다고 튜플로 만들어지는 것이 아님
np.zeros((5,)) # 이렇게 해야 튜플의 형태로 만들어짐
(5) !=(5, )

True

In [ ]:
# np.ones : 1로 채워진 배열 만들기
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(3) * 3 # 원하는 숫자로 채워진 배열을 얻기위해서는 *를 사용해도 됨

array([3., 3., 3.])

In [ ]:
np.full((2, 3), 7) # full을 사용하면 앞쪽에는 shape이 들어가고 뒤에는 지정한 숫자가 들어가게 됨

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
# np.linspace -> 점구간 만들기( 사잇값 만들기 )
np.linspace(1, 10, 3) # 1 ~ 10 까지 3개의 숫자를 균등한 구간으로 만든다. -> 2개의 구간

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random

In [ ]:
# np.random.rand : 완전 랜덤 만들기
np.random.rand(2, 3)

array([[0.31380265, 0.16406678, 0.31920576],
       [0.93274703, 0.56826418, 0.9882754 ]])

In [ ]:
np.random.rand(3, 2, 4)

array([[[0.86809469, 0.37898743, 0.22990623, 0.18123415],
        [0.57235323, 0.21381718, 0.33136243, 0.25310078]],

       [[0.44560489, 0.3845212 , 0.23149466, 0.34641726],
        [0.13285808, 0.97695854, 0.3292979 , 0.51069003]],

       [[0.78584941, 0.11408093, 0.35379099, 0.25593432],
        [0.77740157, 0.72785216, 0.68155069, 0.76546763]]])

In [ ]:
# np.random.randn -> 정규 분포 랜덤 만들기
np.random.randn(16)

array([-1.14657225, -0.73523068, -0.98445916,  1.29067274,  0.11230006,
       -0.00906248, -0.41430838,  0.76249812,  1.88830303,  0.24348812,
        0.62108732, -1.36141067, -0.16513417,  1.30775251,  0.485886  ,
       -1.44248188])

In [ ]:
# np.random.uniform -> 균등 분포 랜덤 만들기
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.1536225 , 1.34012763, 1.85264744, 1.88214646, 1.24111395],
       [2.57628264, 1.26768877, 2.26052384, 2.57024984, 2.21051857],
       [1.32335624, 2.30983307, 1.37619917, 2.18897431, 1.40772919],
       [1.20775166, 1.49887935, 1.03695693, 1.32132569, 2.48959804]])

In [ ]:
# np.random.choice -> 정수 랜덤 샘플링 (모집단을 추출하는 것을 샘플링)
np.random.choice(10, size=(2, 3)) # 0 ~ 9 사이의 정수를 랜덤하게 (2, 3)형태의 배열로 추출

array([[3, 0, 6],
       [6, 0, 1]])

In [ ]:
np.random.choice(10, size=(10, 10)) # 보건 추출 중복된 값이 나와도 됨

array([[0, 4, 4, 9, 7, 0, 4, 6, 2, 6],
       [6, 2, 5, 6, 9, 5, 8, 7, 9, 4],
       [0, 7, 9, 8, 3, 9, 3, 6, 8, 3],
       [9, 1, 6, 4, 1, 1, 2, 6, 8, 8],
       [9, 1, 6, 6, 6, 0, 9, 5, 2, 9],
       [3, 1, 7, 1, 1, 1, 3, 9, 1, 5],
       [8, 8, 0, 8, 2, 0, 2, 8, 4, 8],
       [4, 0, 0, 4, 1, 6, 7, 1, 2, 6],
       [1, 2, 7, 8, 5, 3, 9, 0, 6, 9],
       [0, 7, 7, 3, 3, 7, 0, 9, 5, 0]])

In [ ]:
np.random.choice(10, size=(2, 3), replace=False) # replace=False 을 사용하면 보건 추출을 하지 않게 됨

array([[3, 4, 5],
       [6, 0, 1]])

In [ ]:
np.random.choice(10, size=(10, 10), replace=False) # 보건추출이 아니기 때문에 10,10으로 뽑을 수가 없어서 에러가 나옴

ValueError: Cannot take a larger sample than population when 'replace=False'

In [ ]:
# 정수 랜덤 배열 만들기
np.random.randint(10, 100, size=5) # 열백터로 판단하지만 우리가 볼 때는 행 백터로 보임

array([64, 67, 19, 29, 11])

In [ ]:
np.random.randint(10, 100, size=(3, 4))

array([[24, 45, 97, 48],
       [28, 80, 98, 46],
       [29, 93, 61, 93]])

In [ ]:
# 랜덤 정수 데이터가 5개 있는 열 벡터와, 행 벡터를 만들어 보세요.

np.random.randint(10, 100, size=(5, 1)) # 실제로는 열백터로 취급

array([[34],
       [94],
       [18],
       [26],
       [83]])

In [ ]:
np.random.randint(10, 100, size=(1, 5)) #행 벡터

array([[22, 70, 55, 47, 88]])

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1],
                 [2],
                 [3],
                 [4],
                 [5]])
# 벡터로는 같지만 배열로 봤을 떄는 다른 거임

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2

array([[1],
       [2],
       [3],
       [4],
       [5]])

arr1과 arr2는 같은 배열까요? `No`
  * arr1은 1차원 배열, arr2는 2차원 배열

arr1과 arr2는 같은 **벡터**일까요? `Yes`
  * arr1은 numpy에서는 행벡터의 모양을 하고 있지만 실제로는 열벡터이다.
  * arr2는 열의 수가 1개의 열벡터의 모양을 하고 있다.

대부분의 머신러닝 라이브러리는 기본적인 데이터 취급을 열벡터로 하기 때문에 2차원 배열 이상부터 취급이 가능


# axis 이해하기
axis : 축. 축이란? 데이터가 추가되는 방향의 **인덱스**

예를 들어 3차원 배열 (3, 4, 5)
  * 3차원 배열에 추가되는건 2차원 배열 -> `axis : 0`
  * 2차원 배열에 추가되는건 1차원 배열 -> `axis : 1`
  * 1차원 배열에 추가되는건 0차원 스칼라 -> `axis : 2`


In [ ]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
np.max(arr, axis=0) # 3차원 안에있는 2차원 배열끼리 비교하기 때문에

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=1) # 2차원 안에 있는 1차원 배열끼리 비교하기 때문에

array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=2) # 1차원 안에 있는 스칼라끼리 비교하기 때문에

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

# 인덱스, 슬라이싱

In [ ]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0] # []가 한 번쓰여질 때마다 배열이 낮아지게 됨 0번째의 1차원 배열이 되게 됨

array([1, 2, 3, 4, 5])

In [ ]:
arr[0][2] # 0번째 1차원 배열의 인덱스2인 3이 나오게 됨

3

In [ ]:
arr[0, 2] # arr[0][2]

3

In [ ]:
# 슬라이싱
arr[:] # 전체를 의미하는 거니까 그대로 복사하게 되는 거 1차원 배열 전체라고 생각하면 됨

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[:,2] # 1차원의 전체를 선택하고 그 상태에서 0차원의 2번째를 보여달라

array([3, 8])

In [ ]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
arr[1, 1:3]

array([[16, 17, 18],
       [19, 20, 21]])

In [ ]:
arr[:, 1:3, :2]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20]],

       [[28, 29],
        [31, 32]]])

In [ ]:
# Fancy Indexing
arr = np.arange(24).reshape(4, 3, 2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
# Fancy Indexing : 인덱스를 리스트로 여러 개 지정해서 추출하는 방법

indices = [0, 3]
arr[indices]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
# Spread 연산자
arr = np.arange(36).reshape(2, 3, 3, 2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [ ]:
arr[0, :, :, 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr[0, ..., 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

보통 이미지 데이터를 딥러닝에서 사용하고자 할 때 : `(N, H, W, C)`
* `N` : 이미지의 개수
* `H` : 세로 픽셀의 개수
* `W` : 가로 픽셀의 개수
* `C` : 채널수 (컬러 RGB : 3, 흑백 GRAYSCALE : 1)

In [ ]:
# 예를 들어 가지고 온 이미지 데이터의 모양이 (60000, 28, 28, 1)
#  이미지가 60,000장이 있다.
#  이미지의 세로 크기는 28px
#  이미지의 가로 크기는 28px
#  이미지의 채널은 1채널(grayscale)

# 한장의 흑백 이미지를 그릴 때 필요한 정보는 단순하게 세로, 가로 픽셀의 정보만 있으면 된다.
# images[0, ..., 0] -> ( 28, 28 )

# 배열의 차원(dim)과 형상(shape)

In [ ]:
# 형상(shape)
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
# 배열의 차원을 알아보기
arr.ndim

2

In [ ]:
# 배열이 가지고 있는 모든 스칼라의 개수
arr.size

12

## 차원 수 확장하기

In [ ]:
arr = np.random.rand(3, 3)
arr.shape

(3, 3)

In [ ]:
# 확장되는 차원은 무조건 1을 가짐
arr[np.newaxis, :, :, np.newaxis].shape

(1, 3, 3, 1)

In [ ]:
# 가지고 있는 정보는 h, w(28x28)밖에 없어도 훈련을 할 때는 (n, c, h, w)로 훈련을 해야 함
# 28x28의 이미지를 그대로 쓰는 것이 아니라 (1, 1, 28, 28)로 바꿔서 사용해야한다.
# 이때 형식을 맞춰야할 때 차원 확장을 사용하게 되는 것
# 차원확장은 예측할 때 사용하면 됨

## 차원 쥐어 짜기


In [ ]:
arr = np.random.rand(1, 3, 3, 1)
arr.shape

(1, 3, 3, 1)

In [ ]:
arr_squeeze = np.squeeze(arr)
arr_squeeze.shape # 필요없는 차원을 쥐어 짜서 실제로 모양이 있는 것만 알고 싶을 떄 스퀴즈를 사용함
# 열과 행의 개념이 사라지기 때문에 비정형데이터가 된다. 의미가 있는 행렬은 매트릭

(3, 3)

# 배열의 형상 바꾸기
* `np.newaxis`를 활용하면 축을 하나 추가하게 된다.( 차원 수를 늘린다. )
* `np.squeeze`를 활용하면 개수가 1인 차원의 데이터를 삭제(차원 수를 줄인다.)

평탄화 : 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것 (★★★★★)
* `ravel` : 원본 배열을 평탄화 시킨 **참조**배열을 만들어 낸다. (이를 View 또는 Reference라고 한다.)
* `flatten` : 원본 배열을 평탄화 시킨 **복사된**배열을 만들어 낸다.

**ravel은 원본 배열에 수정이 가해질 가능성이 있고, flatten은 원본 배열에 영향을 미치지 않는다.**

In [ ]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [ ]:
x

array([[14,  4,  9,  0,  5],
       [ 0, 12, 14, 14,  2],
       [ 3, 12,  2, 10,  0]])

## ravel

그림 참조해서 공부

In [ ]:
temp = np.ravel(x) # 2차원에서 1차원이 됨 보이기에만 평탄하게 보이는 것
temp

array([14,  4,  9,  0,  5,  0, 12, 14, 14,  2,  3, 12,  2, 10,  0])

In [ ]:
temp[0] = 100
temp

array([100,   4,   9,   0,   5,   0,  12,  14,  14,   2,   3,  12,   2,
        10,   0])

In [ ]:
x # 원본을 참조하고 있는 배열이기 때문에 원본에 변화가 일어남 원본과 서로 연결되어있기 때문에

array([[100,   4,   9,   0,   5],
       [  0,  12,  14,  14,   2],
       [  3,  12,   2,  10,   0]])

In [ ]:
hex(id(x)), hex(id(temp)), hex(id(temp.base)) # 진짜 모습은 x이므로 메모리 주소값을 찾을 때 temp를 보는 것이 아니라 temp의 base를 봐야함
# 메모리 주소값이 같으면 같은 객체임
# 원본을 실제로 바꿔버리기 때문에 ravel을 잘 쓰지 않음
# 시각화 할 때는 사용함

('0x7f0e288a35d0', '0x7f0e288a3690', '0x7f0e288a35d0')

## flatten

In [ ]:
x = np.random.randint(15, size=(2, 3, 2))
x.shape

(2, 3, 2)

In [ ]:
temp = x.flatten()
temp

array([ 9,  2,  1,  9,  6, 14,  2,  3, 12, 12,  8,  3])

In [ ]:
temp[0] = 100
temp

array([100,   2,   1,   9,   6,  14,   2,   3,  12,  12,   8,   3])

In [ ]:
x # 원본은 유지하면서 실제로 평탄화된 모양의 새로운 배열이 만들어 진것
# ravel과 flatten의 차이점 잘 알아둘 것

array([[[ 9,  2],
        [ 1,  9],
        [ 6, 14]],

       [[ 2,  3],
        [12, 12],
        [ 8,  3]]])

In [ ]:
hex(id(x)), hex(id(temp)), hex(id(temp.base)) # 아예 완벽한 새로운 객체가 만들어진 것

('0x7f0e288a86f0', '0x7f0e288a3f90', '0x59a441c8d3e0')

## reshape
- 배열의 형상을 재구성

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

reshape 팁 : reshape 함수 내의 모든 숫자를 곱했을 때 스칼라 원소의 개수(size)와 같아야 합니다.

In [ ]:
x.reshape(2, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(3, 5, 1) # 원소의 개수가 다르기 때문에 reshape이 되지 않음

ValueError: cannot reshape array of size 20 into shape (3,5,1)

-1을 사용하면 남은 숫자를 자동으로 계산

In [ ]:
x.reshape(2, -1, 2) # -1 위치의 값이 알아서 계산된다.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(2, 2, -1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
x.reshape(3, 5, -1) # 어떤 것을 곱하든 맞춰지지 않기 때문에 에러 뜸, 스칼라 값의 약수여야 함

ValueError: cannot reshape array of size 20 into shape (3,5,newaxis)

In [ ]:
x.reshape(2, -1, -1) # -1은 한번밖에 못씀 2개 이상 쓰면 에러 뜸

ValueError: can only specify one unknown dimension

In [ ]:
x = np.arange(36).reshape(3,4,3) # 3차원배열을 2차원으로 바꾸는 것도 가능
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [ ]:
x.reshape(3, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
x.reshape(-1) # -1만 사용해도 평탄화가 가능 함

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
x.reshape(-1, 1) # 열벡터로 만들기

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35]])

In [ ]:
x.reshape(1, -1) # 행벡터로 만들기

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35]])

# 브로드캐스팅
- 차원 수가 다른 배열끼리 연산
* 차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능
* 저차원 배열을 고차원 배열로 **확장**
* 수학적으로 따지게 되면, 고차원 배열의 shape과 똑같은 1벡터(ones)를 만들어서 저차원 배열과 곱한 배열을 만들어서 계산

In [ ]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
a + 3 # 차원이 다르기 때문에 계산이 안되어야하는 것이 맞지만 계산이 되는 이유는
# 3이라는 숫자가 브로드캐스팅(흩뿌려져서) 모든 숫자들에 +3이 되는 것 그림참조!!

array([3, 4, 5])

In [ ]:
# shape이 다를 때의 연산
a = np.arange(12).reshape(4, 3) # (4, 3)
b = np.arange(100, 103)         # (3, )
c = np.arange(1000, 1004)       # (4, )
d = b.reshape(1, 3)             # (1, 3)
e = np.arange(0, 4).reshape(4, 1) # ( 4, 1)

In [ ]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + c # 저차원의 원소의 값(더해야할 개수)은 같아야지 가능함

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [ ]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + e # 옆으로 브로드캐스팅(퍼지면)하면 되기 때문에 가능

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
e = np.array([[0, 0],[1, 1],[2, 2],[3, 3]])

a + e

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 